### ISSUE TITLE
Possible Issue With Examples / Documentation

### ISSUE THREAD

**Issue by drwhitehouse** [phe-bioinformatics/PneumoCaT#12]
Hi, I've installed PneumoCaT using the documentation in the pdf.
Rather than using Miniconda, I used Anaconda.
Firstly I installed all the dependencies in a venv and then I cloned the git repo.
Working through the examples I get the following:

```
aaw945@dn103:~/weekly/PneumoCaT (master u=)$ python ./PneumoCaT.py -i Examples/PHESPV0253
  File "./PneumoCaT.py", line 123
    print "Unexpected number (" + str(len(fastq_files)) + ") of fastq files. Please use options -1 and -2 to specify the path to the fastq files"
                              ^
SyntaxError: invalid syntax
aaw945@dn103:~/weekly/PneumoCaT (master u=)$ ls
Documentation  Examples  LICENSE  modules  PneumoCaT.py  README.md  streptococcus-pneumoniae-ctvdb
aaw945@dn103:~/weekly/PneumoCaT (master u=)$ ls Examples/PHESPV0253/
PHESPV0253.R1.fastq.gz  PHESPV0253.R2.fastq.gz  PHESPV0253.results.xml
```
Any assistance would be appreciated.

**Comment by grovesn** [comment]
Hi,

Please can you let me know what version of all the software you are using?
Please make sure you are using python2 and not python3

Thanks,
Natalie

**Comment by drwhitehouse** [comment]
Aah. I think a python mismatch may be the issue. Thanks for responding.
