### ISSUE TITLE
Update to Python 3?

### ISSUE THREAD

**Issue by russellsmithies** [phe-bioinformatics/PneumoCaT#17]
Any chance you could update the code to Python 3? Your requirement for Python 2.7 makes it very difficult (almost impossible) to use bioconda pneumocat along with other bioconda applications (such as 'seroba') in the same environment.
Also Python 2.7 goes end of life in a few months so some future planning might be a good idea.

**Comment by grovesn** [comment]
Thank you for your suggestion.
As this repository is provided as a courtesy to the community our first priority is that it is stable in the compute environment we have within the clinical service and therefore is not under "active" development outside of this.
We are obviously aware of the move towards python 3 and this update is planned for the future but as I said, this will be primarily driven by the clinical service. The public repository will be updated as and when this happens but at the moment I cannot give you a definitive time frame for this.

Thanks again for you comments,
Natalie

**Comment by tseemann** [comment]
@grovesn 

```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
```

Getting closer!

**Comment by quacksawbones** [comment]
Any update on this?
