### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by noisrevni** [phe-bioinformatics/PneumoCaT#21]
Hello,

Thank you for your previous answer, and I have a new question now.

When I ran PneumoCaT, it printed: 
`running bowtie index`
`['24F', '24B']`
`Traceback (most recent call last):`
`  File "PneumoCaT.py", line 164, in <module> main(opts)`
`  File "PneumoCaT.py", line 159, in main`
`    SNP_based_Serotyping_Functions.find_serotype(opts.input_directory, fastq_files, hits, reference_directory, opts.output_dir, opts.bowtie, opts.samtools, opts.cleanup, logger, workflow=workflow, version=version, threads=opts.threads)`
`  File "/home/ziyi/PneumoCaT/modules/SNP_based_Serotyping_Functions.py", line 1066, in find_serotype
    fastq = [f for f in fastq_files if f.find('1.fastq') != -1][0]`
`IndexError: list index out of range`

What is puzzling is that I was able to run successfully before, but when I expanded the memory module for the computer, the second stage could not run normally.

Waiting for your kind response, thank you!

**Comment by noisrevni** [comment]
![P1](https://user-images.githubusercontent.com/67349504/96423015-5a21f280-122b-11eb-8726-4ede13abcbcf.png)
![P2](https://user-images.githubusercontent.com/67349504/96423155-80e02900-122b-11eb-9f30-ec63c5cc61c9.png)
[pneumo_capsular_typing.stderr.txt](https://github.com/phe-bioinformatics/PneumoCaT/files/5400439/pneumo_capsular_typing.stderr.txt)
[pneumo_capsular_typing.stdout.txt](https://github.com/phe-bioinformatics/PneumoCaT/files/5400440/pneumo_capsular_typing.stdout.txt)

**Comment by noisrevni** [comment]
And this is another printed:

`(py2718) ziyi@ziyi-virtual-machine:~/PneumoCaT$ python PneumoCaT.py -i /home/ziyi/PneumoCaT/BatchFour/ZY08
running bowtie index`
`['18B', '18C', '18A']`
`Settings:`
`  Output files:` `"/home/ziyi/PneumoCaT/BatchFour/ZY08/pneumo_capsular_typing/SNP_based_serotyping/ZY08_FDSW202284189-1r_1_tmp/reference.fasta.*.bt2"`
`  Line rate: 6 (line is 64 bytes)`
`  Lines per side: 1 (side is 64 bytes)`
`  Offset rate: 4 (one in 16)`
`  FTable chars: 10`
`  Strings: unpacked`
`  Max bucket size: default`
`  Max bucket size, sqrt multiplier: default`
`  Max bucket size, len divisor: 4`
`  Difference-cover sample period: 1024`
`  Endianness: little`
`  Actual local endianness: little`
`  Sanity checking: disabled`
`  Assertions: disabled`
`  Random seed: 0`
`  Sizeofs: void*:8, int:4, long:8, size_t:8`
`Input files DNA, FASTA:`
`  /home/ziyi/PneumoCaT/BatchFour/ZY08/pneumo_capsular_typing/SNP_based_serotyping/ZY08_FDSW202284189-1r_1_tmp/reference.fasta`
`Building a SMALL index`
`Reading reference sizes`
`  Time reading reference sizes: 00:00:00`
`Calculating joined length`
`Writing header`
`Reserving space for joined string`
`Joining reference sequences`
`  Time to join reference sequences: 00:00:00`
`bmax according to bmaxDivN setting: 548`
`Using parameters --bmax 411 --dcv 1024`
`  Doing ahead-of-time memory usage test`
`  Passed!  Constructing with these parameters: --bmax 411 --dcv 1024`
`Constructing suffix-array element generator`
`Building DifferenceCoverSample`
`  Building sPrime`
`  Building sPrimeOrder`
`  V-Sorting samples`
`  V-Sorting samples time: 00:00:00`
`  Allocating rank array`
`  Ranking v-sort output`
`  Ranking v-sort output time: 00:00:00`
`  Invoking Larsson-Sadakane on ranks`
`  Invoking Larsson-Sadakane on ranks time: 00:00:00`
`  Sanity-checking and returning`
`Building samples`
`Reserving space for 12 sample suffixes`
`Generating random suffixes`
`QSorting 12 sample offsets, eliminating duplicates`
`QSorting sample offsets, eliminating duplicates time: 00:00:00`
`Multikey QSorting 12 samples`
`  (Using difference cover)`
`  Multikey QSorting samples time: 00:00:00`
`Calculating bucket sizes`
`Splitting and merging`
`  Splitting and merging time: 00:00:00`
`Avg bucket size: 2193 (target: 410)`
`Converting suffix-array elements to index image`
`Allocating ftab, absorbFtab`
`Entering Ebwt loop`
`Getting block 1 of 1`
`  No samples; assembling all-inclusive block`
`  Sorting block of length 2193 for bucket 1`
`  (Using difference cover)`
`  Sorting block time: 00:00:00`
`Returning block of 2194 for bucket 1`
`Exited Ebwt loop`
`fchr[A]: 0`
`fchr[C]: 708`
`fchr[G]: 973`
`fchr[T]: 1396`
`fchr[$]: 2193`
`Exiting Ebwt::buildToDisk()`
`Returning from initFromVector`
`Wrote 4195279 bytes to primary EBWT file:` `/home/ziyi/PneumoCaT/BatchFour/ZY08/pneumo_capsular_typing/SNP_based_serotyping/ZY08_FDSW202284189-1r_1_tmp/reference.fasta.1.bt2`
`Wrote 556 bytes to secondary EBWT file:` `/home/ziyi/PneumoCaT/BatchFour/ZY08/pneumo_capsular_typing/SNP_based_serotyping/ZY08_FDSW202284189-1r_1_tmp/reference.fasta.2.bt2`
`Re-opening _in1 and _in2 as input streams`
`Returning from Ebwt constructor`
`Headers:`
`    len: 2193`
`    bwtLen: 2194`
`    sz: 549`
`    bwtSz: 549`
`    lineRate: 6`
`    offRate: 4`
`    offMask: 0xfffffff0`
`    ftabChars: 10`
`    eftabLen: 20`
`    eftabSz: 80`
`    ftabLen: 1048577`
`    ftabSz: 4194308`
`    offsLen: 138`
`    offsSz: 552`
`    lineSz: 64`
`    sideSz: 64`
`    sideBwtSz: 48`
`    sideBwtLen: 192`
`    numSides: 12`
`    numLines: 12`
`    ebwtTotLen: 768`
`    ebwtTotSz: 768`
`    color: 0`
`    reverse: 0`
`Total time for call to driver() for forward index: 00:00:00`
`Reading reference sizes`
`  Time reading reference sizes: 00:00:00`
`Calculating joined length`
`Writing header`
`Reserving space for joined string`
`Joining reference sequences`
`  Time to join reference sequences: 00:00:00`
`  Time to reverse reference sequence: 00:00:00`
`bmax according to bmaxDivN setting: 548`
`Using parameters --bmax 411 --dcv 1024`
`  Doing ahead-of-time memory usage test`
`  Passed!  Constructing with these parameters: --bmax 411 --dcv 1024`
`Constructing suffix-array element generator`
`Building DifferenceCoverSample`
`  Building sPrime`
`  Building sPrimeOrder`
`  V-Sorting samples`
`  V-Sorting samples time: 00:00:00`
`  Allocating rank array`
`  Ranking v-sort output`
`  Ranking v-sort output time: 00:00:00`
`  Invoking Larsson-Sadakane on ranks`
`  Invoking Larsson-Sadakane on ranks time: 00:00:00`
`  Sanity-checking and returning`
`Building samples`
`Reserving space for 12 sample suffixes`
`Generating random suffixes`
`QSorting 12 sample offsets, eliminating duplicates`
`QSorting sample offsets, eliminating duplicates time: 00:00:00`
`Multikey QSorting 12 samples`
`  (Using difference cover)`
`  Multikey QSorting samples time: 00:00:00`
`Calculating bucket sizes`
`Splitting and merging`
`  Splitting and merging time: 00:00:00`
`Avg bucket size: 2193 (target: 410)`
`Converting suffix-array elements to index image`
`Allocating ftab, absorbFtab`
`Entering Ebwt loop`
`Getting block 1 of 1`
`  No samples; assembling all-inclusive block`
`  Sorting block of length 2193 for bucket 1`
`  (Using difference cover)`
`  Sorting block time: 00:00:00`
`Returning block of 2194 for bucket 1`
`Exited Ebwt loop`
`fchr[A]: 0`
`fchr[C]: 708`
`fchr[G]: 973`
`fchr[T]: 1396`
`fchr[$]: 2193`
`Exiting Ebwt::buildToDisk()`
`Returning from initFromVector`
`Wrote 4195279 bytes to primary EBWT file:` `/home/ziyi/PneumoCaT/BatchFour/ZY08/pneumo_capsular_typing/SNP_based_serotyping/ZY08_FDSW202284189-1r_1_tmp/reference.fasta.rev.1.bt2`
`Wrote 556 bytes to secondary EBWT file:` `/home/ziyi/PneumoCaT/BatchFour/ZY08/pneumo_capsular_typing/SNP_based_serotyping/ZY08_FDSW202284189-1r_1_tmp/reference.fasta.rev.2.bt2`
`Re-opening _in1 and _in2 as input streams`
`Returning from Ebwt constructor`
`Headers:`
`    len: 2193`
`    bwtLen: 2194`
`    sz: 549`
`    bwtSz: 549`
`    lineRate: 6`
`    offRate: 4`
`    offMask: 0xfffffff0`
`    ftabChars: 10`
`    eftabLen: 20`
`    eftabSz: 80`
`    ftabLen: 1048577`
`    ftabSz: 4194308`
`    offsLen: 138`
`    offsSz: 552`
`    lineSz: 64`
`    sideSz: 64`
`    sideBwtSz: 48`
`    sideBwtLen: 192`
`    numSides: 12`
`    numLines: 12`
`    ebwtTotLen: 768`
`    ebwtTotSz: 768`
`    color: 0`
`    reverse: 1`
`Total time for backward call to driver() for mirror index: 00:00:00`
`3675845 reads; of these:`
`  3675845 (100.00%) were paired; of these:`
`    3674807 (99.97%) aligned concordantly 0 times`
`    1038 (0.03%) aligned concordantly exactly 1 time`
`    0 (0.00%) aligned concordantly >1 times`
`    ----`
`    3674807 pairs aligned concordantly 0 times; of these:`
`      356 (0.01%) aligned discordantly 1 time`
`    ----`
`    3674451 pairs aligned 0 times concordantly or discordantly; of these:`
`      7348902 mates make up the pairs; of these:`
`        7347669 (99.98%) aligned 0 times`
`        1233 (0.02%) aligned exactly 1 time`
`        0 (0.00%) aligned >1 times`
`0.05% overall alignment rate`
`[bam_sort_core] merging from 0 files and 4 in-memory blocks...`
`/home/ziyi/anaconda3/envs/py2718/lib/python2.7/site-packages/Bio/Seq.py:2715: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.`
`  BiopythonWarning)`

**Comment by CarmenSheppard** [comment]
> Hello,
> 
> Thank you for your previous answer, and I have a new question now.
> 
> When I ran PneumoCaT, it printed:
> `running bowtie index`
> `['24F', '24B']`
> `Traceback (most recent call last):`
> ` File "PneumoCaT.py", line 164, in <module> main(opts)`
> ` File "PneumoCaT.py", line 159, in main`
> ` SNP_based_Serotyping_Functions.find_serotype(opts.input_directory, fastq_files, hits, reference_directory, opts.output_dir, opts.bowtie, opts.samtools, opts.cleanup, logger, workflow=workflow, version=version, threads=opts.threads)`
> ` File "/home/ziyi/PneumoCaT/modules/SNP_based_Serotyping_Functions.py", line 1066, in find_serotype fastq = [f for f in fastq_files if f.find('1.fastq') != -1][0]`
> `IndexError: list index out of range`
> 
> What is puzzling is that I was able to run successfully before, but when I expanded the memory module for the computer, the second stage could not run normally.
> 
> Waiting for your kind response, thank you!

Hi,

  For this serogroup 24 this looks like it's just the fastq files - you seem to have "1.clean.fastq" they need to be "1.fastq".  The memory module shouldn't make any difference.  The tool cannot tell between 24F and 24B anyway as we have not yet been able to identify any serotype specific features that are consistent between the two serotypes. 


Is there a problem with the serogroup 18 that you show the output from in the other screenshots etc? It looks like normal run output to me?
Thanks

Carmen

**Comment by noisrevni** [comment]
Thank you very much, Carmen.

It is indeed a problem caused by the fastq file name, and you completely solved my problem.

Again, Thank you for your prompt reply.
