### ISSUE TITLE
Pneumocat - not running

### ISSUE THREAD

**Issue by srhsjh** [phe-bioinformatics/PneumoCaT#25]
Hi,
I am trying to run PneumoCaT using unbuntu and python version 2.7.11. I have followed the set up instructions and installed the dependencies:
Bowtie2
samtools1.9
PyYaml
numpy
lxml
pysam
biopython
I have cloned the PneumoCaT repository.
When I try and run the help or examples I get this error message:

File "PneumoCaT.py", line 31, in <module>
import Serotype_determier_functions
File "/home/simon/PneumoCaT/modules/Serotype_determiner_functions.py", line 16, in <module> import pysam
ImportError: no module named pysam

I am new to using these systems so it might be something simple I have not done but would appreciate any advice to move my project forward.

Many thanks,
Simon

**Comment by CarmenSheppard** [comment]
Hi, 
Can you run 'module list' and see what modules are loaded in the environment?
Did pysam successfully install? have you made sure that the version you are using is for python 2.7?

I currently use an older version of python but hopefully this will not matter but these are the versions I have in my environment on our hpc. 
 
  1) python/2.7.6               3) numpy/python2.7/1.7.1      5) lxml/python2.7/3.2.3       7) yaml/1.1
  2) bowtie2/2.2.3              4) biopython/python2.7/1.70   6) pysam/python2.7/0.8.3      8) samtools/1.3

**Comment by srhsjh** [comment]
Hi,
Many thanks for your response. It just took me a while to figure it all out.
conda create -n "pneumocat" python=2.7
conda activate pneumocat
conda install -c bioconda pneumocat
PneumoCaT.py
Have manged to download the programme.
