### ISSUE TITLE
assemblies as input?

### ISSUE THREAD

**Issue by abrozzi** [phe-bioinformatics/PneumoCaT#26]
Is it possible in PneumoCaT ?

Alex

**Comment by CarmenSheppard** [comment]
No sorry, PneumoCat works with mapping so it's not possible to use assemblies as input.  I have a new (lite) tool in initial testing which can take assembly inputs however it cannot determine as many serotypes to type level as PneumoCaT and also requires a bit more tweaking on the database, But you are welcome to try it out if you like  - please validate the outputs if you do for your own use. - it's VERY fast when run on assemblies  which is an advantage. https://github.com/CarmenSheppard/PneumoKITy
